/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as FrotaIndexRouteImport } from './routes/frota/index'
import { Route as FrotaSlugRouteImport } from './routes/frota/$slug'
import { Route as ServicosIndexRouteImport } from './routes/servicos/index'
import { Route as ServicosSlugRouteImport } from './routes/servicos/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotaIndexRoute = FrotaIndexRouteImport.update({
  id: '/frota/',
  path: '/frota/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotaSlugRoute = FrotaSlugRouteImport.update({
  id: '/frota/$slug',
  path: '/frota/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/servicos/$slug',
  path: '/servicos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/frota/$slug': typeof FrotaSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/frota/': typeof FrotaIndexRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/frota/$slug': typeof FrotaSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/blog': typeof BlogIndexRoute
  '/frota': typeof FrotaIndexRoute
  '/servicos': typeof ServicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/frota/$slug': typeof FrotaSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/frota/': typeof FrotaIndexRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/politica-de-privacidade'
    | '/blog/$slug'
    | '/frota/$slug'
    | '/servicos/$slug'
    | '/blog/'
    | '/frota/'
    | '/servicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/politica-de-privacidade'
    | '/blog/$slug'
    | '/frota/$slug'
    | '/servicos/$slug'
    | '/blog'
    | '/frota'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/politica-de-privacidade'
    | '/blog/$slug'
    | '/frota/$slug'
    | '/servicos/$slug'
    | '/blog/'
    | '/frota/'
    | '/servicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  BlogSlugRoute: typeof BlogSlugRoute
  FrotaSlugRoute: typeof FrotaSlugRoute
  ServicosSlugRoute: typeof ServicosSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  FrotaIndexRoute: typeof FrotaIndexRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frota/': {
      id: '/frota/'
      path: '/frota'
      fullPath: '/frota/'
      preLoaderRoute: typeof FrotaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frota/$slug': {
      id: '/frota/$slug'
      path: '/frota/$slug'
      fullPath: '/frota/$slug'
      preLoaderRoute: typeof FrotaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/servicos/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  BlogSlugRoute: BlogSlugRoute,
  FrotaSlugRoute: FrotaSlugRoute,
  ServicosSlugRoute: ServicosSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  FrotaIndexRoute: FrotaIndexRoute,
  ServicosIndexRoute: ServicosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
